spring:
  application:
    name: lbs_ckBoard03

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: C##user1
    password: 1234

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB


  security:
    oauth2:
      client:
        registration:
          google:
#            client-id: ${GOOGLE_CLIENT_ID}  --
#            client-secret: ${GOOGLE_CLIENT_SECRET}            
            scope:
              - email
              - profile
        provider:
            google:

server:
  port: 8090
  servlet:
    session:
      timeout: 360000
  tomcat:
    max-parameter-count: 10000

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: com.springboot.ckb.**.domain

logging:
  config: classpath:config/logback-spring.xml
  level:
    org.springframework.web: DEBUG

jwt:
  issuer: "leebs126@gmail.com"
  secret-key: "dev-springboot-secret-key-for-jwt-token-1234567890"


#관리자 계정 설정 
admin:
  ids:
    - admin
    - admin001
    - master
    - system

# 회원가입 금지 키워드
signup:
  forbidden-keywords: admin,master,system
